name: Basic CI

on:
  push:
    branches:
      - feature-ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check app file
        run: cat app.txt